// Isolated Hub and mocked native recycling: never operate on personal cards.
import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, cp } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createService } from '../server.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
await cp(path.join(root, 'public/assets'), path.join(root, 'dist/assets'), { recursive: true });
const base = await mkdtemp(path.join(root, '.cache/cards-ui-')), repo = path.join(base, 'hub');
for (const folder of ['workspace', 'knowledge', 'processes', 'inbox']) await mkdir(path.join(repo, folder), { recursive: true });
await writeFile(path.join(repo, 'workspace/workspace.json'), JSON.stringify({ entities: [] }));
const external = path.join(base, 'unity'), second = path.join(base, 'blender'); await mkdir(external); await mkdir(second);
const service = await createService({ repo, uiDir: path.join(root, 'dist') });
let browser;
try {
  const project = await service.projects.save({ name: 'Game X', repositoryPath: external });
  const linked = await service.projects.saveRepository({ projectId: project.id, name: 'Blender', repositoryPath: second });
  const card = await service.projects.createCard({ title: 'Models', projectId: project.id, repositoryId: linked.id });
  const other = await service.projects.createCard({ title: 'Overview', projectId: project.id });
  const request = (route, data) => fetch(`${service.origin}/api${route}`, { method: 'POST', headers: { Authorization: `Bearer ${service.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
  await request('/settings', { selectedProjectId: project.id, accentTheme: 'blue' });
  browser = await chromium.launch({ headless: true, channel: 'msedge' });
  const page = await browser.newPage({ viewport: { width: 1280, height: 850 } }); page.setDefaultTimeout(12000); page.setDefaultNavigationTimeout(30000);
  await page.route('https://fonts.googleapis.com/**', route => route.abort());
  await page.route('https://fonts.gstatic.com/**', route => route.abort());
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  page.on('dialog', () => assert.fail('Card confirmation must not use a browser dialog'));
  await page.goto(service.urls.workspace, { waitUntil: 'domcontentloaded' });
  await page.getByRole('button', { name: 'Workspace · Game X', exact: true }).waitFor();
  await page.locator(`[data-entity="${card.id}"]`).click({ button: 'right' });
  await page.getByRole('menuitem', { name: 'Archive card', exact: true }).click();
  await page.locator(`[data-entity="${card.id}"]`).waitFor({ state: 'hidden' });
  await page.goto(service.urls.workspace + `#/${card.id}`);
  await page.getByRole('button', { name: 'Actions for card Models' }).click();
  await page.getByRole('menuitem', { name: 'Restore card' }).click();
  await page.getByRole('button', { name: 'Workspace · Game X', exact: true }).click();
  await page.locator(`[data-entity="${card.id}"]`).waitFor();
  await page.getByRole('button', { name: 'Actions for card Models' }).click();
  await page.getByRole('menuitem', { name: 'Delete card…' }).click();
  const dialog = page.getByRole('alertdialog'); await dialog.waitFor();
  await page.screenshot({ path: path.join(base, 'delete-card.png'), fullPage: true });
  await dialog.getByRole('button', { name: 'Cancel' }).click();
  assert.equal((await service.projects.list()).length, 1);
  await page.getByRole('button', { name: 'Actions for card Models' }).click();
  await page.getByRole('menuitem', { name: 'Delete card…' }).click();
  await dialog.getByRole('button', { name: 'Delete card', exact: true }).click();
  await page.locator(`[data-entity="${card.id}"]`).waitFor({ state: 'hidden' });
  assert.ok(JSON.parse(await readFile(service.projects.workspacePath, 'utf8')).entities.some(item => item.id === other.id));
  await page.getByRole('button', { name: 'Toggle projects', exact: true }).click();
  await page.getByRole('button', { name: 'Edit Game X', exact: true }).click();
  await page.getByRole('button', { name: 'Remove registration', exact: true }).click();
  await dialog.getByText('1 affected card', { exact: true }).waitFor();
  await dialog.getByText('Overview', { exact: true }).waitFor();
  await page.screenshot({ path: path.join(base, 'remove-workspace.png'), fullPage: true });
  await dialog.getByRole('button', { name: 'Remove registration', exact: true }).click();
  await page.getByRole('button', { name: 'Workspace · Global Hub', exact: true }).waitFor();
  assert.equal(JSON.parse(await readFile(service.projects.workspacePath, 'utf8')).entities[0].projectId, null);
  assert.deepEqual(errors, []);
  console.log(`Card actions, themed confirmations and workspace breadcrumb passed; screenshots: ${base}`);
} finally { await browser?.close(); await service.close(); }
