import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from '@playwright/test';
import { createService } from '../server.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const base = await mkdtemp(path.join(os.tmpdir(), 'mrmak-claude-ui-'));
const repo = path.join(base, 'hub'), linked = path.join(base, 'Unity'), home = path.join(base, 'home');
for (const folder of [path.join(repo, 'workspace'), path.join(linked, '.claude', 'skills', 'report'), path.join(home, '.claude')]) await mkdir(folder, { recursive: true });
await writeFile(path.join(repo, 'workspace', 'workspace.json'), JSON.stringify({ entities: [] }));
await writeFile(path.join(linked, '.claude', 'skills', 'report', 'SKILL.md'), '---\nname: report\ndescription: Test reporting\n---\n');
await writeFile(path.join(home, '.claude', 'settings.json'), JSON.stringify({ enabledPlugins: { 'fixture@test': true } }));
await writeFile(path.join(home, '.claude.json'), JSON.stringify({ mcpServers: { fixture_server: { type: 'http', url: 'https://example.test/mcp' } } }));
const service = await createService({ repo, uiDir: path.join(root, 'dist'), mcpOptions: { home, env: {} } });
let browser;
try {
  const project = await service.projects.save({ name: 'Game', repositoryPath: linked });
  browser = await chromium.launch({ headless: true, channel: process.env.MRMAK_TEST_BROWSER || 'msedge' });
  const page = await browser.newPage({ viewport: { width: 1100, height: 820 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(service.urls.workspace);
  await page.getByRole('button', { name: 'Toggle skills' }).click();
  await page.getByLabel('Active workspace').selectOption(project.id);
  await page.getByRole('button', { name: 'Claude', exact: true }).click();
  await page.getByRole('button', { name: 'Linked project', exact: true }).click();
  await page.getByText('Claude skill controls', { exact: false }).click();
  const setting = page.getByRole('combobox', { name: 'report native Claude setting' });
  await setting.click(); await page.getByRole('option', { name: 'Off', exact: true }).click();
  await page.waitForFunction(() => [...document.querySelectorAll('[role=combobox]')].some(item => item.getAttribute('aria-label') === 'report native Claude setting' && item.textContent.includes('Off')));
  assert.equal(JSON.parse(await readFile(path.join(linked, '.claude', 'settings.local.json'), 'utf8')).skillOverrides.report, 'off');
  await page.getByRole('button', { name: 'Toggle mcp' }).click();
  await page.getByRole('combobox', { name: 'fixture_server global Claude MCP' }).click();
  await page.getByRole('option', { name: 'Off', exact: true }).click();
  await page.getByRole('combobox', { name: 'fixture_server global Claude MCP' }).getByText('Off', { exact: true }).waitFor();
  assert.equal(JSON.parse(await readFile(path.join(home, '.claude.json'), 'utf8')).mcpServers.fixture_server, undefined);
  await page.getByRole('combobox', { name: 'fixture global Claude setting' }).click();
  await page.getByRole('option', { name: 'Off', exact: true }).click();
  await page.getByRole('combobox', { name: 'fixture global Claude setting' }).getByText('Off', { exact: true }).waitFor();
  assert.equal(JSON.parse(await readFile(path.join(home, '.claude', 'settings.json'), 'utf8')).enabledPlugins['fixture@test'], false);
  await page.locator('.mcp-scroll').evaluate(element => { element.scrollTop = 0; });
  await page.screenshot({ path: path.join(base, 'claude-tools.png') });
  let quick;
  await page.route('**/api/chats/quick', async route => { quick = route.request().postDataJSON(); await route.fulfill({ json: { id: 'fixture-only' } }); });
  await page.getByRole('button', { name: 'New Claude chat', exact: true }).click();
  await page.waitForTimeout(150);
  assert.equal(quick.agent, 'claude'); assert.equal(quick.projectId, project.id);
  assert.deepEqual(errors, []);
  console.log('Claude UI passed: native skill, global MCP, plugin toggles and quick-chat routing. All configuration was isolated; no agent/model started.');
} finally { await browser?.close(); service.sessions.items.clear(); await service.close(); }
