import test from 'node:test';
import assert from 'node:assert/strict';
import os from 'node:os';
import path from 'node:path';
import { mkdtemp, mkdir, readFile, writeFile } from 'node:fs/promises';
import { parse as toml } from 'smol-toml';
import { Projects } from '../projects.mjs';
import { CodexMcpEditor } from '../codex-mcp-editor.mjs';
import { CodexScopes } from '../codex-scopes.mjs';

test('managed Codex MCP definitions are scoped, reversible and do not rewrite foreign settings', async () => {
  const base = await mkdtemp(path.join(os.tmpdir(), 'mrmak-mcp-editor-'));
  const hub = path.join(base, 'hub'), repo = path.join(base, 'game'), home = path.join(base, 'home');
  await mkdir(hub);
  await mkdir(path.join(home, '.codex'), { recursive: true });
  await mkdir(path.join(repo, '.codex'), { recursive: true });
  const globalFile = path.join(home, '.codex', 'config.toml'), projectFile = path.join(repo, '.codex', 'config.toml');
  await writeFile(globalFile, '# personal comment\n[mcp_servers.foreign]\ncommand = "foreign"\n');
  await writeFile(projectFile, '# project comment\nmodel_verbosity = "low"\n');
  const projects = new Projects(hub, path.join(hub, '.mrmak'));
  const project = await projects.save({ name: 'Game', repositoryPath: repo });
  const options = { home, env: { CODEX_HOME: path.join(home, '.codex') } };
  const editor = new CodexMcpEditor(projects, options);
  await editor.change({ scope: 'project', projectId: project.id, action: 'save', name: 'local', transport: 'stdio', command: 'node', args: ['server.mjs'], enabled: true });
  await editor.change({ scope: 'global', action: 'save', name: 'shared', transport: 'http', url: 'https://example.org/mcp', enabled: false });
  const scopes = new CodexScopes(projects, options);
  await scopes.set(project.id, { kind: 'mcp', id: 'foreign', enabled: false });
  assert.equal(toml(await readFile(projectFile, 'utf8')).mcp_servers.local.args[0], 'server.mjs');
  assert.equal(toml(await readFile(projectFile, 'utf8')).mcp_servers.foreign.enabled, false);
  assert.equal(toml(await readFile(globalFile, 'utf8')).mcp_servers.shared.url, 'https://example.org/mcp');
  assert.match(await readFile(globalFile, 'utf8'), /# personal comment/);
  assert.deepEqual((await editor.list('project', project.id)).servers.map(item => item.name), ['local']);
  await assert.rejects(editor.change({ scope: 'global', action: 'save', name: 'foreign', transport: 'stdio', command: 'other' }), /outside Mr. Mik/);
  await editor.change({ scope: 'project', projectId: project.id, action: 'toggle', name: 'local', enabled: false });
  assert.equal(toml(await readFile(projectFile, 'utf8')).mcp_servers.local.enabled, false);
  await editor.change({ scope: 'project', projectId: project.id, action: 'remove', name: 'local' });
  assert.equal(toml(await readFile(projectFile, 'utf8')).mcp_servers.local, undefined);
  assert.equal(toml(await readFile(projectFile, 'utf8')).mcp_servers.foreign.enabled, false);
});
