import assert from 'node:assert/strict';
import { cp, mkdtemp, mkdir, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from '@playwright/test';
import { randomUUID } from 'node:crypto';
import { createService } from '../server.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const base = await mkdtemp(path.join(os.tmpdir(), 'mrmak-mak-ui-'));
const repo = path.join(base, 'hub'), linked = path.join(base, 'Unity');
await mkdir(path.join(repo, 'workspace'), { recursive: true }); await mkdir(linked);
await writeFile(path.join(repo, 'workspace', 'workspace.json'), JSON.stringify({ entities: [] }));
const uiDir = path.join(base, 'ui');
await cp(path.join(root, 'dist'), uiDir, { recursive: true });
await cp(path.join(root, 'public', 'assets'), path.join(uiDir, 'assets'), { recursive: true });
const service = await createService({ repo, uiDir, mcpOptions: { home: path.join(base, 'home'), env: {} } });
let browser;
try {
  const project = await service.projects.save({ name: 'Game X', repositoryPath: linked });
  await service.projects.createCard({ projectId: project.id, title: 'Unity Work', repositoryId: 'primary' });
  const mak = service.coordinator;
  let turn = 0;
  mak.start = async () => { if (!mak.child) { mak.child = { kill() {} }; mak.threadId = 'global'; mak.threads.set('global', 'global'); } };
  mak.rpc = async (method, params) => {
    if (method === 'model/list') return { data: [{ model: 'fixture-model', isDefault: true, defaultReasoningEffort: 'medium', supportedReasoningEfforts: ['low', 'medium', 'high', 'xhigh', 'max'].map(reasoningEffort => ({ reasoningEffort })) }, { model: 'fixture-other', displayName: 'Other model', defaultReasoningEffort: 'high', supportedReasoningEfforts: ['low', 'high'].map(reasoningEffort => ({ reasoningEffort })) }], nextCursor: null };
    if (method === 'config/read') return { config: { model: 'fixture-model' } };
    if (method === 'thread/start' || method === 'thread/fork') return { thread: { id: randomUUID() } };
    if (method === 'thread/resume') return { thread: { id: params.threadId } };
    if (method === 'turn/interrupt') return {};
    assert.equal(method, 'turn/start'); const global = turn++ > 0;
    setTimeout(async () => {
      try {
        const scope = mak.active.scope, id = mak.active.operationId;
        assert.equal(scope.projectId, project.id);
        await mak.execute('hub_action', { name: 'mrmak_create_resource', args: { kind: 'knowledge', title: global ? 'Global Lesson' : 'Workspace Lesson', text: 'A fixture lesson.', scope: global ? 'global' : 'workspace' } }, id, undefined, scope);
        await mak.message({ method: 'item/completed', params: { threadId: params.threadId, item: { type: 'agentMessage', text: 'Lesson saved in the Hub.' } } });
        await mak.message({ method: 'turn/completed', params: { threadId: params.threadId, turn: { status: 'completed' } } });
      } catch (error) { mak.active?.reject(error); }
    }, 20);
    return { turn: { id: `turn-${turn}` } };
  };
  browser = await chromium.launch({ headless: true, channel: process.env.MRMAK_TEST_BROWSER || 'msedge' });
  const page = await browser.newPage({ viewport: { width: 1100, height: 850 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(service.urls.workspace);
  await page.getByRole('button', { name: 'Toggle files' }).click();
  await page.getByRole('button', { name: 'Toggle Mik', exact: true }).click();
  assert.equal(await page.locator('.files-rail [aria-label="Toggle mak"]').count(), 0);
  const launcher = await page.locator('.mak-launcher').boundingBox();
  const surface = await page.locator('.workspace-surface').boundingBox();
  assert.ok(launcher.width <= 44 && Math.abs(surface.x + surface.width - launcher.x - launcher.width - 18) < 2);
  await page.getByLabel('Active workspace').selectOption(project.id);
  await page.getByRole('combobox', { name: 'Mik card' }).click(); await page.getByRole('option', { name: 'Unity Work', exact: true }).click();
  await page.locator('.mak-working-target').getByText('Main project', { exact: true }).waitFor();
  assert.equal(await page.getByRole('combobox', { name: 'Mik working project' }).count(), 0);
  await page.getByRole('textbox', { name: 'Message Mik' }).fill('Save a workspace lesson');
  await page.getByRole('combobox', { name: 'Mik reasoning', exact: true }).click();
  await page.getByRole('option', { name: 'Low', exact: true }).click();
  await page.getByRole('combobox', { name: 'Mik model', exact: true }).click();
  await page.getByRole('option', { name: 'Other model', exact: true }).click();
  await page.getByRole('combobox', { name: 'Mik model', exact: true }).getByText('Other model', { exact: true }).waitFor();
  assert.equal(mak.conversation(project.id).model, 'fixture-other');
  await page.getByRole('button', { name: 'Send to Mik' }).click();
  await page.getByText('Lesson saved in the Hub.', { exact: true }).waitFor();
  await page.getByRole('textbox', { name: 'Message Mik' }).fill('Save a global lesson');
  await page.getByRole('button', { name: 'Send to Mik' }).click();
  await page.getByRole('group', { name: 'Mik confirmation' }).waitFor();
  assert.equal(await page.getByRole('combobox', { name: 'Mik reasoning', exact: true }).isDisabled(), true);
  assert.equal(await page.getByRole('combobox', { name: 'Mik model', exact: true }).isDisabled(), true);
  await page.locator('.mak-composer').getByRole('button', { name: 'Stop Mik request' }).waitFor();
  assert.equal(await page.getByRole('button', { name: 'Send to Mik' }).count(), 0);
  assert.equal(await page.getByRole('button', { name: 'Stop request', exact: true }).count(), 0);
  await page.getByRole('button', { name: 'Activity', exact: true }).click();
  await page.getByRole('group', { name: 'Mik confirmation' }).waitFor();
  assert.equal(await page.getByRole('textbox', { name: 'Message Mik' }).count(), 0);
  await page.getByRole('button', { name: 'Conversation', exact: true }).click();
  assert.equal((await service.projects.resources('knowledge', null, 'relevant')).length, 0);
  await page.waitForTimeout(250);
  await page.screenshot({ path: path.join(base, 'mak-confirmation.png') });
  await page.getByRole('button', { name: 'Approve', exact: true }).click();
  await page.waitForFunction(() => document.querySelectorAll('.mak-answer').length === 2);
  assert.equal((await service.projects.resources('knowledge', null, 'relevant')).length, 1);
  await page.getByLabel('Active workspace').selectOption('');
  await page.getByText('Ask Mik to organize cards', { exact: false }).waitFor();
  await page.getByLabel('Active workspace').selectOption(project.id);
  await page.waitForFunction(() => document.querySelectorAll('.mak-answer').length === 2);
  await page.getByRole('button', { name: 'Activity', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: 'Message Mik' }).count(), 0);
  assert.equal(await page.getByRole('combobox', { name: 'Mik card' }).count(), 0);
  await page.getByText('Terminal attention requests and exits for this workspace appear here.', { exact: true }).waitFor();
  await page.getByRole('button', { name: 'Conversation', exact: true }).click();
  await page.getByRole('button', { name: 'Close Mik', exact: true }).click();
  await page.getByRole('button', { name: 'Toggle Mik', exact: true }).click();
  await page.waitForFunction(() => document.querySelectorAll('.mak-answer').length === 2);
  await page.waitForTimeout(250);
  await page.screenshot({ path: path.join(base, 'mak-history.png') });
  const original = mak.conversation(project.id).id;
  await page.getByRole('button', { name: 'Fork Mik conversation', exact: true }).click();
  await page.waitForFunction(() => document.querySelectorAll('.mak-answer').length === 2);
  await page.waitForTimeout(150);
  assert.equal(mak.conversation(project.id).parentId, original);
  assert.equal(mak.conversation(project.id).effort, 'low');
  assert.equal(mak.conversation(project.id).model, 'fixture-other');
  await page.getByRole('button', { name: 'New Mik conversation', exact: true }).click();
  await page.getByText('Ask Mik to organize cards', { exact: false }).waitFor();
  assert.equal(mak.history(project.id, mak.conversation(project.id).id).length, 0);
  assert.equal(mak.conversation(project.id).effort, 'medium');
  await page.getByRole('button', { name: 'Mik conversation History', exact: true }).click();
  await page.getByRole('combobox', { name: 'Mik saved conversations' }).click();
  await page.getByRole('option', { name: 'Save a workspace lesson', exact: true }).click();
  await page.waitForFunction(() => document.querySelectorAll('.mak-answer').length === 2);
  assert.equal(mak.conversation(project.id).id, original);
  await page.getByRole('button', { name: 'Collapse files', exact: true }).click();
  await page.setViewportSize({ width: 520, height: 700 });
  await page.waitForTimeout(250);
  const panel = await page.locator('.mak-panel').boundingBox();
  assert.ok(panel.x >= 0 && panel.y >= 0 && panel.x + panel.width <= 520 && panel.y + panel.height < 700);
  await page.screenshot({ path: path.join(base, 'mak-compact.png') });
  await page.getByRole('textbox', { name: 'Message Mik' }).fill('Cancel this fixture request');
  await page.getByRole('button', { name: 'Send to Mik' }).click();
  await page.getByRole('group', { name: 'Mik confirmation' }).waitFor();
  await page.locator('.mak-composer').getByRole('button', { name: 'Stop Mik request' }).click();
  await page.getByRole('button', { name: 'Send to Mik' }).waitFor();
  assert.equal((await service.projects.resources('knowledge', null, 'relevant')).length, 1);
  await page.setViewportSize({ width: 1100, height: 850 });
  await page.getByRole('button', { name: 'Toggle settings', exact: true }).click();
  await page.getByRole('combobox', { name: 'Default worker reasoning · Codex', exact: true }).click();
  await page.getByRole('option', { name: 'Low', exact: true }).click();
  await page.getByRole('combobox', { name: 'Default worker reasoning · Claude', exact: true }).click();
  await page.getByRole('option', { name: 'Max', exact: true }).click();
  await page.getByRole('combobox', { name: 'Coordinator reasoning', exact: true }).click();
  await page.getByRole('option', { name: 'Extra high', exact: true }).click();
  await page.waitForTimeout(150);
  assert.equal(mak.settings().defaultWorkerEffort, 'low');
  assert.equal(mak.settings().defaultClaudeWorkerEffort, 'max');
  assert.equal(mak.settings().coordinatorEffort, 'xhigh');
  assert.equal(mak.conversation(project.id).effort, 'low');
  await page.screenshot({ path: path.join(base, 'reasoning-settings.png') });
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ result: 'Mik UI: scoped conversation, card/project defaults, Bridge writes, real UI approval, workspace switching and restored History passed. Model protocol was simulated; no CLI or model request.', screenshots: base }));
} finally { await browser?.close(); await service.close(); }
