// UI smoke with fake PTYs/picker replies. Native TUI is tested separately.
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, cp } from 'node:fs/promises';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';
import { chromium } from '@playwright/test';
import { createService } from '../server.mjs';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..'), base = await mkdtemp(path.join(os.tmpdir(), 'mik-opencode-chat-ui-'));
const repo = path.join(base, 'hub'), uiDir = path.join(base, 'ui'), linked = path.join(base, 'working');
await mkdir(path.join(repo, 'workspace'), { recursive: true }); await mkdir(linked);
await writeFile(path.join(repo, 'workspace/workspace.json'), JSON.stringify({ entities: [] }));
await cp(path.join(root, 'dist'), uiDir, { recursive: true }); await cp(path.join(root, 'public/assets'), path.join(uiDir, 'assets'), { recursive: true });
const service = await createService({ repo, uiDir, restoreSessions: false, mcpOptions: { home: path.join(base, 'home'), env: {} } });
let browser;
try {
  const project = await service.projects.save({ name: 'Fixture workspace', repositoryPath: linked });
  service.sessions.launch = async session => { session.process = { write() {}, resize() {}, kill() {} }; session.nativeId = `ses_${session.id.replaceAll('-', '')}`; session.openCodeLaunchId = 'fixture'; session.status = 'running'; service.sessions.changed(session); };
  const source = service.sessions.make({ id: randomUUID(), name: 'OpenCode fixture', agent: 'opencode', cwd: linked, projectId: project.id, repositoryId: 'primary', nativeId: 'ses_source', status: 'running', activity: 'idle', open: true, cols: 90, rows: 32, createdAt: new Date().toISOString(), openCodeLaunchId: 'fixture' });
  source.preview = 'OpenCode final preview fixture'; source.hasConversation = true;
  source.process = { write() {}, resize() {}, kill() {} }; await service.sessions.hydrate(source); service.sessions.items.set(source.id, source);
  const family = service.sessions.make({ id: randomUUID(), name: 'Family fixture', agent: 'opencode', cwd: linked, nativeId: 'ses_familyui', status: 'stopped', open: false, hasConversation: true, createdAt: new Date().toISOString() }); service.sessions.items.set(family.id, family);
  browser = await chromium.launch({ headless: true, channel: process.env.MRMAK_TEST_BROWSER || 'msedge' });
  const page = await browser.newPage({ viewport: { width: 700, height: 780 } }), errors = [], controls = [], picks = [];
  page.on('pageerror', error => errors.push(error.stack || error.message));
  let deleted;
  await page.route('**/api/sessions/*/deleteplan', route => {
    assert.ok(route.request().url().includes(family.id));
    return route.fulfill({ json: { token: 'fixture-plan', agent: 'opencode', chatName: family.name, nativeId: family.nativeId, bytes: 2048, files: [], nativeSessions: [{ id: 'ses_familyui', title: 'Main fixture' }, { id: 'ses_childui', title: 'Child fixture' }, { id: 'ses_grandchildui', title: 'Grandchild fixture' }], warning: 'These three native sessions will be deleted recursively.' } });
  });
  await page.route('**/api/sessions/*/deletenative', route => { deleted = route.request().postDataJSON(); return route.fulfill({ json: { deleted: true, agent: 'opencode' } }); });
  await page.route('**/api/sessions/*/*-picker', async route => {
    const data = route.request().postDataJSON(), variant = route.request().url().includes('reasoning'); picks.push(data);
    await route.fulfill({ json: data.action === 'open' ? { options: (variant ? ['Default', 'high'] : ['Fixture Alpha', 'Fixture Beta']).map((label, i) => ({ key: String(i), slug: String(i), label, current: i === 0 })) } : { confirmed: true, variantMenu: !variant && data.action === 'choose' } });
  });
  await page.route('**/api/sessions/*/control', async route => { controls.push(route.request().postDataJSON().action); await route.fulfill({ json: { accepted: true } }); });
  await page.goto(service.urls.chats);
  const refreshes = [];
  await page.route('**/api/sessions/*/toolsrefresh', async route => {
    refreshes.push(route.request().url()); source.toolRefresh = { status: 'applied', reason: 'MCP connections updated without restarting.', automatic: false }; service.sessions.changed(source);
    await route.fulfill({ json: { applied: true, mode: 'live' } });
  });
  source.toolRefresh = { status: 'pending', reason: 'MCP settings changed. Apply after the request finishes.', automatic: false }; source.activity = 'working'; service.sessions.changed(source);
  const refreshButton = page.getByRole('button', { name: 'Apply native configuration to this chat', exact: true });
  await refreshButton.waitFor(); assert.equal(await refreshButton.isDisabled(), true);
  source.activity = 'idle'; service.sessions.changed(source);
  await page.waitForFunction(() => !document.querySelector('[aria-label="Apply native configuration to this chat"]')?.disabled);
  await refreshButton.click(); await page.getByText('MCP connections updated without restarting.', { exact: true }).waitFor();
  assert.equal(refreshes.length, 1); assert.ok(refreshes[0].includes(source.id)); assert.equal(source.nativeId, 'ses_source');
  source.toolRefresh = null; service.sessions.changed(source);
  const layouts = [];
  await page.route('**/api/window', route => { layouts.push(route.request().postDataJSON()); return route.fulfill({ json: { requested: true } }); });
  await page.getByRole('button', { name: 'Restore default window layout', exact: true }).click();
  assert.deepEqual(layouts, [{ window: 'chats', action: 'layout' }]);
  await page.getByRole('button', { name: 'Cursor diagnostics', exact: true }).click();
  const report = page.getByLabel('Cursor diagnostic report'); await report.waitFor();
  await page.locator('.xterm-helper-textarea').focus();
  await page.waitForFunction(() => JSON.parse(document.querySelector('[aria-label="Cursor diagnostic report"]').textContent).lastFocused?.inputFocused === true);
  await page.getByRole('button', { name: 'Model ▾', exact: true }).focus();
  await page.waitForFunction(() => {
    const data = JSON.parse(document.querySelector('[aria-label="Cursor diagnostic report"]').textContent);
    return !data.inputFocused && data.lastFocused?.inputFocused === true && typeof data.lastFocused.renderer.boxShadow === 'string';
  });
  const focused = JSON.parse(await report.innerText());
  assert.ok(['bar', 'outline', 'underline', 'block', 'unknown'].includes(focused.lastFocused.renderer.effectiveStyle));
  assert.equal('caretBorder' in focused.renderer, false);
  const frame = '\x1b[?1049h\x1b[H\x1b[2JFullscreen header\x1b[10;4HInput draft preserved\x1b[20;1HFullscreen footer\x1b[10;25H\x1b[2 q\x1b]12;#1e1e1e\x07\x1b[?25h';
  await new Promise(resolve => source.terminal.write(frame, resolve)); source.pendingOutput += frame; service.sessions.flushOutput(source);
  await page.locator('.xterm-helper-textarea').focus();
  await page.waitForFunction(() => {
    const data = JSON.parse(document.querySelector('[aria-label="Cursor diagnostic report"]').textContent);
    return data.inputFocused && data.renderer.effectiveStyle === 'block' && data.renderer.boxShadow.includes('inset') && data.renderer.boxShadow !== 'none';
  });
  const screenBeforeClear = await page.locator('.xterm-rows').innerText();
  const cursorBeforeClear = JSON.parse(await report.innerText()).cursor;
  const backgroundBeforeClear = JSON.parse(await report.innerText()).renderer.background;
  await service.sessions.clearScreen(source.id);
  await page.waitForTimeout(500);
  assert.equal(await page.locator('.xterm-rows').innerText(), screenBeforeClear);
  const afterClear = JSON.parse(await report.innerText());
  assert.deepEqual(afterClear.cursor, cursorBeforeClear);
  assert.equal(afterClear.buffer, 'alternate');
  assert.equal(afterClear.renderer.background, backgroundBeforeClear, 'Clear does not reset native cursor color');
  await page.screenshot({ path: path.join(base, 'cursor-clear-preserved.png') });
  await new Promise(resolve => source.terminal.write('\x1b[?25l', resolve)); source.pendingOutput += '\x1b[?25l'; service.sessions.flushOutput(source);
  await page.waitForFunction(() => JSON.parse(document.querySelector('[aria-label="Cursor diagnostic report"]').textContent).cursor.hidden === true);
  assert.equal(await page.locator('.xterm-cursor').count(), 0, 'The contrast bar never forces a hidden native cursor to appear');
  assert.equal((await report.innerText()).includes('OpenCode final preview fixture'), false);
  await new Promise(resolve => source.terminal.write('\x1b[?25h', resolve)); source.pendingOutput += '\x1b[?25h'; service.sessions.flushOutput(source);
  await page.waitForFunction(() => JSON.parse(document.querySelector('[aria-label="Cursor diagnostic report"]').textContent).cursor.hidden === false);
  await page.locator('.cursor-diagnostics').getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('button', { name: 'Model ▾', exact: true }).click();
  await page.getByRole('textbox', { name: 'Find a native model', exact: true }).fill('Beta');
  await page.locator('.chat-model-menu').getByRole('button', { name: 'Fixture Beta', exact: true }).click();
  await page.locator('.chat-model-menu').getByRole('button', { name: 'high', exact: true }).click();
  assert.ok(picks.some(item => item.model === '1')); assert.ok(picks.some(item => item.effort === '1')); assert.equal(source.effort, undefined);
  await page.getByRole('button', { name: 'Send typed CLI prompt', exact: true }).click();
  source.activity = 'working'; service.sessions.changed(source);
  await page.getByRole('button', { name: 'Interrupt response', exact: true }).click(); assert.deepEqual(controls, ['submit', 'interrupt']);
  source.activity = 'idle'; service.sessions.changed(source);
  await page.getByRole('button', { name: 'Fork selected conversation', exact: true }).click();
  await page.getByRole('tab', { name: /Fork · OpenCode fixture/ }).waitFor();
  const fork = service.sessions.list().find(chat => chat.name === 'Fork · OpenCode fixture'); assert.notEqual(fork.nativeId, source.nativeId); assert.equal(fork.projectId, project.id);
  await page.screenshot({ path: path.join(base, 'chat-controls.png') });
  await page.getByRole('button', { name: 'History', exact: true }).click();
  await page.getByText('OpenCode final preview fixture', { exact: true }).waitFor();
  await page.screenshot({ path: path.join(base, 'history-preview.png') });
  const familyRow = page.locator('.history-item').filter({ hasText: 'Family fixture' });
  await familyRow.locator('summary').click(); await familyRow.getByRole('button', { name: 'Delete native chat…', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: 'Permanently delete native chat' });
  await dialog.getByText('3 native database sessions', { exact: false }).waitFor();
  assert.equal(await dialog.locator('li').count(), 3);
  assert.equal(await dialog.getByRole('button', { name: 'Delete permanently', exact: true }).isDisabled(), true);
  await dialog.getByRole('textbox').fill('Family fixture'); await page.screenshot({ path: path.join(base, 'family-delete.png') });
  await dialog.getByRole('button', { name: 'Delete permanently', exact: true }).click(); await dialog.waitFor({ state: 'hidden' });
  assert.deepEqual(deleted, { token: 'fixture-plan', name: 'Family fixture' });
  await page.goto(service.urls.workspace); await page.getByRole('button', { name: 'New OpenCode chat', exact: true }).waitFor();
  assert.equal(await page.locator('.topbar').getByRole('button', { name: 'Restore default window layout', exact: true }).count(), 0);
  await page.locator('.files-rail').getByRole('button', { name: 'Restore default window layout', exact: true }).click();
  assert.deepEqual(layouts[1], { window: 'workspace', action: 'layout' });
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ result: 'PASS: OpenCode Model/Variant, Send/Stop, fork, History, complete family deletion review and shortcuts; no native CLI/provider started.', screenshot: path.join(base, 'family-delete.png') }));
} finally { await browser?.close(); for (const session of service.sessions.items.values()) session.process = null; await service.close(); }
