import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, realpath } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from '@playwright/test';
import { createService } from '../server.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const base = await realpath(await mkdtemp(path.join(os.tmpdir(), 'mik-opencode-ui-')));
const repo = path.join(base, 'hub'), home = path.join(base, 'home'), linked = path.join(base, 'linked');
for (const folder of [path.join(repo, 'workspace'), path.join(repo, '.agents/skills/report'), path.join(linked, '.opencode/skills/native-report'), path.join(home, '.config/opencode')]) await mkdir(folder, { recursive: true });
await writeFile(path.join(repo, 'workspace/workspace.json'), JSON.stringify({ entities: [] }));
await writeFile(path.join(repo, '.agents/skills/report/SKILL.md'), '---\nname: report\ndescription: UI reporting fixture\n---\nInstructions.');
await writeFile(path.join(linked, '.opencode/skills/native-report/SKILL.md'), '---\nname: native-report\ndescription: UI native fixture\n---\nInstructions.');
await writeFile(path.join(home, '.config/opencode/opencode.json'), JSON.stringify({ mcp: { fixture: { type: 'local', command: ['node', 'fixture.mjs'], enabled: true } } }));
const service = await createService({ repo, uiDir: path.join(root, 'dist'), mcpOptions: { home, env: {} } });
let browser;
try {
  const project = await service.projects.save({ name: 'Fixture Workspace', repositoryPath: linked });
  await service.projects.setHubSkillScope({ id: 'report', agent: 'opencode', scope: 'global', enabled: true });
  browser = await chromium.launch({ headless: true, channel: process.env.MRMAK_TEST_BROWSER || 'msedge' });
  const page = await browser.newPage({ viewport: { width: 1100, height: 900 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(service.urls.workspace);
  await page.getByRole('button', { name: 'Toggle skills' }).click();
  await page.getByRole('button', { name: 'OpenCode', exact: true }).click();
  await page.getByLabel('Active workspace').selectOption(project.id);
  await page.getByLabel('report project setting').selectOption('off');
  await page.getByLabel('report project setting').selectOption('inherited');
  await page.getByRole('button', { name: 'Linked project', exact: true }).click();
  await page.getByText('OpenCode skill controls', { exact: false }).click();
  await page.getByRole('combobox', { name: 'native-report native OpenCode setting' }).click();
  await page.getByRole('option', { name: 'Off', exact: true }).click();
  await page.getByRole('combobox', { name: 'native-report native OpenCode setting' }).getByText('Off', { exact: true }).waitFor();
  assert.equal(JSON.parse(await readFile(path.join(linked, 'opencode.json'), 'utf8')).permission.skill['native-report'], 'deny');
  await page.getByRole('button', { name: 'Toggle mcp' }).click();
  await page.getByRole('combobox', { name: 'fixture project OpenCode setting' }).click();
  await page.getByRole('option', { name: 'Off', exact: true }).click();
  await page.getByRole('combobox', { name: 'fixture project OpenCode setting' }).getByText('Off', { exact: true }).waitFor();
  assert.equal(JSON.parse(await readFile(path.join(linked, 'opencode.json'), 'utf8')).mcp.fixture.enabled, false);
  await page.getByRole('button', { name: 'Add MCP server', exact: false }).click();
  await page.getByRole('button', { name: 'OpenCode', exact: true }).click();
  await page.getByLabel('Server name', { exact: true }).fill('created');
  await page.getByLabel('Command', { exact: true }).fill('node');
  await page.getByRole('button', { name: 'Save definition', exact: true }).click();
  await page.getByText('created · stdio', { exact: true }).waitFor();
  assert.equal(JSON.parse(await readFile(path.join(linked, 'opencode.json'), 'utf8')).mcp.created.type, 'local');
  await page.screenshot({ path: path.join(base, 'opencode-controls.png') });
  assert.deepEqual(errors, []);
  console.log('PASS: OpenCode Hub override/inherit, native skill Off, MCP project Off and definition creation from UI. Isolated folders; no CLI/model started.');
} finally { await browser?.close(); await service.close(); }
