import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rename } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from '@playwright/test';
import { createService } from '../server.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const base = await mkdtemp(path.join(os.tmpdir(), 'mrmak-project-ui-'));
const repo = path.join(base, 'hub'), external = path.join(base, 'Exercise'), blender = path.join(base, 'Blender'), home = path.join(base, 'home');
for (const folder of [external, blender, ...['workspace', 'knowledge', 'processes', 'inbox', 'projects'].map(folder => path.join(repo, folder))]) await mkdir(folder, { recursive: true });
await mkdir(path.join(repo, '.agents/skills/handoff'), { recursive: true });
await writeFile(path.join(repo, '.agents/skills/handoff/SKILL.md'), '---\nname: handoff\ndescription: Project handoff cards.\n---\n');
await mkdir(path.join(repo, '.claude/skills/handoff'), { recursive: true });
await writeFile(path.join(repo, '.claude/skills/handoff/SKILL.md'), '---\nname: handoff\ndescription: Claude handoff cards.\n---\n');
await mkdir(path.join(home, '.codex/plugins/cache/local/unity/1.0'), { recursive: true });
await writeFile(path.join(home, '.codex/config.toml'), '[plugins."unity@local"]\nenabled = false\n[mcp_servers.unityMCP]\ncommand = "uvx"\n');
await writeFile(path.join(repo, 'workspace/workspace.json'), JSON.stringify({ entities: [] }));
await writeFile(path.join(repo, 'knowledge/general.md'), '# Shared lesson');
await writeFile(path.join(repo, 'inbox/reference.txt'), 'original bytes');
const source = path.join(external, 'reference.md'); await writeFile(source, '# Project knowledge');
const service = await createService({ repo, uiDir: path.join(root, 'dist'), mcpOptions: { home, env: { CODEX_HOME: path.join(home, '.codex') } } });
let browser;
try {
  const project = await service.projects.save({ name: 'Exercise', repositoryPath: external });
  const missingFolder = path.join(base, 'Temporarily-missing');
  await mkdir(missingFolder);
  const missingProject = await service.projects.save({ name: 'Missing folder', repositoryPath: missingFolder });
  await rename(missingFolder, `${missingFolder}-moved`);
  const linked = await service.projects.saveRepository({ projectId: project.id, name: 'Blender', repositoryPath: blender });
  await writeFile(path.join(blender, 'model.blend'), 'fixture model');
  await service.projects.importResource({ kind: 'knowledge', projectId: project.id, source });
  await service.projects.assignResource({ kind: 'inbox', path: 'inbox/reference.txt', projectId: project.id });
  browser = await chromium.launch({ headless: true, channel: process.env.MRMAK_TEST_BROWSER || 'msedge' });
  const page = await browser.newPage({ viewport: { width: 1100, height: 800 } });
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(service.urls.workspace);
  await page.getByRole('button', { name: 'Toggle files' }).click();
  await page.getByLabel('Active workspace').selectOption(missingProject.id);
  await page.waitForFunction(id => document.querySelector('select[aria-label="Active workspace"]')?.value === id, missingProject.id);
  await page.getByLabel('Active workspace').selectOption(project.id);
  await page.getByRole('button', { name: 'reference.md' }).waitFor();
  const screenshot = path.join(base, 'project-rail.png'); await page.screenshot({ path: screenshot });
  await page.getByRole('button', { name: 'Toggle inbox' }).click();
  await page.getByRole('button', { name: 'reference.txt' }).waitFor();
  await page.getByRole('button', { name: 'Toggle files' }).click();
  await page.getByRole('button', { name: 'Create card' }).click();
  await page.getByLabel('Card title').fill('Gameplay Notes');
  await page.getByRole('combobox', { name: 'Card category' }).click();
  await page.getByRole('listbox', { name: 'Card category' }).getByRole('option', { name: 'Research' }).click();
  await page.getByRole('combobox', { name: 'Card linked project' }).click();
  await page.getByRole('listbox', { name: 'Card linked project' }).getByRole('option', { name: 'Blender' }).click();
  await page.screenshot({ path: path.join(base, 'card-create-dialog.png') });
  await page.setViewportSize({ width: 590, height: 780 });
  await page.screenshot({ path: path.join(base, 'card-create-dialog-narrow.png') });
  await page.setViewportSize({ width: 1100, height: 800 });
  await page.getByRole('dialog', { name: 'New card' }).getByRole('button', { name: 'Create card' }).click();
  await page.getByRole('link', { name: 'Gameplay Notes' }).waitFor();
  assert.equal(JSON.parse(await readFile(service.projects.workspacePath, 'utf8')).entities[0].projectId, project.id);
  assert.equal(JSON.parse(await readFile(service.projects.workspacePath, 'utf8')).entities[0].category, 'research');
  assert.equal(JSON.parse(await readFile(service.projects.workspacePath, 'utf8')).entities[0].repositoryId, linked.id);
  const pinned = page.waitForResponse(response => response.url().endsWith('/api/cards/pin'));
  await page.getByRole('button', { name: 'Pin card Gameplay Notes' }).click();
  assert.equal((await pinned).status(), 200);
  await page.getByRole('link', { name: 'Gameplay Notes' }).click();
  await page.getByRole('button', { name: 'Unpin card Gameplay Notes' }).waitFor();
  const cardId = JSON.parse(await readFile(service.projects.workspacePath, 'utf8')).entities[0].id;
  const quickChatRequests = [];
  const mockQuickChat = route => { quickChatRequests.push(route.request().postDataJSON()); return route.fulfill({ status: 201, contentType: 'application/json', body: JSON.stringify({ id: 'mock-quick-chat' }) }); };
  await page.route('**/api/chats/quick', mockQuickChat);
  const cardQuickChat = page.waitForResponse(response => response.url().endsWith('/api/chats/quick'));
  await page.getByRole('button', { name: 'New Codex chat', exact: true }).click();
  await cardQuickChat;
  assert.deepEqual(quickChatRequests[0], { projectId: project.id, cardId });
  assert.equal(await page.getByRole('heading', { name: 'New chat' }).count(), 0);
  await page.getByRole('button', { name: 'Workspace', exact: true }).click();
  await page.locator('.mak-card-cover[aria-label="Gameplay Notes"]').waitFor();
  const homeQuickChat = page.waitForResponse(response => response.url().endsWith('/api/chats/quick'));
  await page.getByRole('button', { name: 'New Codex chat', exact: true }).click();
  await homeQuickChat;
  assert.deepEqual(quickChatRequests[1], { projectId: project.id, cardId: null });
  await page.unroute('**/api/chats/quick', mockQuickChat);
  assert.equal(JSON.parse(await readFile(service.projects.workspacePath, 'utf8')).entities[0].pinned, true);
  await page.getByRole('button', { name: 'Toggle mcp' }).click();
  await page.getByText('unity@local', { exact: true }).waitFor();
  await page.getByLabel('unity@local project setting').selectOption('true');
  await page.waitForFunction(() => document.querySelector('select[aria-label="unity@local project setting"]')?.value === 'true');
  await page.waitForTimeout(500);
  assert.match(await readFile(path.join(external, '.codex/config.toml'), 'utf8'), /enabled = true/);
  await page.getByRole('combobox', { name: 'Linked project for tools' }).click();
  await page.getByRole('listbox', { name: 'Linked project for tools' }).getByRole('option', { name: 'Blender' }).click();
  assert.match(await page.getByRole('combobox', { name: 'Linked project for tools' }).innerText(), /Blender/);
  assert.equal(await page.getByLabel('Filter tools by type').locator('option[value="skill"]').count(), 0);
  await page.getByLabel('Filter MCP by scope').selectOption('project');
  assert.equal(await page.getByLabel('Project for tools', { exact: true }).count(), 0);
  await page.getByRole('button', { name: 'Toggle skills' }).click();
  const hubSkills = page.getByRole('region', { name: 'Skill management' });
  const skillLocation = page.getByRole('group', { name: 'Skill location' });
  const skillAgent = page.getByRole('group', { name: 'Skill agent' });
  assert.equal(await skillLocation.getByRole('button', { name: 'Hub' }).getAttribute('aria-pressed'), 'true');
  assert.match(await page.getByLabel('Folder path').inputValue(), /[\\/]\.agents[\\/]skills$/);
  await hubSkills.getByText('handoff', { exact: true }).waitFor();
  assert.equal(await hubSkills.getByRole('button', { name: 'Exercise' }).count(), 0);
  assert.equal(await page.getByRole('button', { name: 'Open codex folder' }).count(), 0);
  const skillSaved = page.waitForResponse(response => response.url().endsWith('/api/hub/skills/scope'));
  await hubSkills.getByLabel('handoff project setting').selectOption('on');
  assert.equal((await skillSaved).status(), 200);
  assert.equal(JSON.parse(await readFile(path.join(repo, 'projects/skill-scopes.json'), 'utf8')).skills.handoff.projects[project.id], true);
  await page.getByLabel('Active workspace').selectOption('');
  const globalSkillSaved = page.waitForResponse(response => response.url().endsWith('/api/hub/skills/scope'));
  await hubSkills.getByLabel('handoff global setting').selectOption('on');
  assert.equal((await globalSkillSaved).status(), 200);
  await page.getByLabel('Active workspace').selectOption(project.id);
  await hubSkills.getByLabel('handoff project setting').waitFor();
  await page.waitForFunction(() => document.querySelector('select[aria-label="handoff project setting"]')?.value === 'on');
  assert.equal(await hubSkills.getByLabel('handoff project setting').inputValue(), 'on');
  assert.equal(await hubSkills.getByLabel('handoff project setting').isDisabled(), false);
  const localSkillFirstInherit = page.waitForResponse(response => response.url().endsWith('/api/hub/skills/scope'));
  await hubSkills.getByLabel('handoff project setting').selectOption('inherited');
  assert.equal((await localSkillFirstInherit).status(), 200);
  await page.waitForFunction(() => document.querySelector('select[aria-label="handoff project setting"]')?.value === 'inherited');
  const localSkillOff = page.waitForResponse(response => response.url().endsWith('/api/hub/skills/scope'));
  await hubSkills.getByLabel('handoff project setting').selectOption('off');
  assert.equal((await localSkillOff).status(), 200);
  await page.waitForFunction(() => document.querySelector('select[aria-label="handoff project setting"]')?.value === 'off');
  assert.equal(JSON.parse(await readFile(path.join(repo, 'projects/skill-scopes.json'), 'utf8')).skills.handoff.projects[project.id], false);
  const localSkillInherit = page.waitForResponse(response => response.url().endsWith('/api/hub/skills/scope'));
  await hubSkills.getByLabel('handoff project setting').selectOption('inherited');
  assert.equal((await localSkillInherit).status(), 200);
  await page.waitForFunction(() => document.querySelector('select[aria-label="handoff project setting"]')?.value === 'inherited');
  assert.equal(Object.hasOwn(JSON.parse(await readFile(path.join(repo, 'projects/skill-scopes.json'), 'utf8')).skills.handoff.projects, project.id), false);
  await skillLocation.getByRole('button', { name: 'Linked project' }).click();
  assert.equal(await hubSkills.count(), 0);
  await page.getByLabel('Native skill linked project').selectOption(linked.id);
  assert.match(await page.getByLabel('Folder path').inputValue(), /Blender[\\/]\.agents[\\/]skills$/);
  await page.getByLabel('Native skill linked project').selectOption('primary');
  assert.match(await page.getByLabel('Folder path').inputValue(), /Exercise[\\/]\.agents[\\/]skills$/);
  await skillLocation.getByRole('button', { name: 'Hub' }).click();
  assert.equal(await hubSkills.count(), 1);
  await hubSkills.getByText('handoff', { exact: true }).waitFor();
  assert.match(await page.getByLabel('Folder path').inputValue(), /[\\/]\.agents[\\/]skills$/);
  await page.screenshot({ path: path.join(base, 'skills-codex.png') });
  await skillAgent.getByRole('button', { name: 'Claude' }).click();
  await hubSkills.getByText('handoff', { exact: true }).waitFor();
  const claudeSkillSaved = page.waitForResponse(response => response.url().endsWith('/api/hub/skills/scope'));
  await hubSkills.getByLabel('handoff project setting').selectOption('on');
  assert.equal((await claudeSkillSaved).status(), 200);
  assert.equal(JSON.parse(await readFile(path.join(repo, 'projects/skill-scopes.json'), 'utf8')).claudeSkills.handoff.projects[project.id], true);
  assert.equal(await page.getByRole('button', { name: 'MR-MAK root' }).count(), 0);
  await page.getByRole('button', { name: 'Add skill' }).click();
  await page.getByRole('button', { name: 'Linked project skill' }).click();
  await page.getByLabel('Skill linked project', { exact: true }).selectOption(linked.id);
  await page.getByLabel('Skill name').fill('blender-handoff');
  await page.getByLabel('When should it be used?').fill('Use when handing off Blender assets.');
  await page.getByLabel('Instructions').fill('# Blender handoff\n\nCheck the target folder.');
  await page.getByRole('button', { name: 'Create skill' }).click();
  await page.getByRole('region', { name: 'Add skill' }).waitFor({ state: 'hidden' });
  assert.match(await readFile(path.join(blender, '.claude/skills/blender-handoff/SKILL.md'), 'utf8'), /Blender handoff/);
  assert.equal(await skillLocation.getByRole('button', { name: 'Linked project' }).getAttribute('aria-pressed'), 'true');
  assert.match(await page.getByLabel('Folder path').inputValue(), /Blender[\\/]\.claude[\\/]skills[\\/]blender-handoff$/);
  await skillLocation.getByRole('button', { name: 'Hub' }).click();
  await page.getByRole('button', { name: 'Add skill' }).click();
  await page.getByLabel('Skill name').fill('workspace-brief');
  await page.getByLabel('When should it be used?').fill('Use when preparing a workspace brief.');
  await page.getByLabel('Instructions').fill('# Workspace brief\n\nSummarize progress.');
  await page.getByRole('button', { name: 'Create skill' }).click();
  await page.getByRole('region', { name: 'Add skill' }).waitFor({ state: 'hidden' });
  assert.match(await readFile(path.join(repo, '.claude/skills/workspace-brief/SKILL.md'), 'utf8'), /Workspace brief/);
  assert.equal(JSON.parse(await readFile(path.join(repo, 'projects/skill-scopes.json'), 'utf8')).claudeSkills['workspace-brief'].projects[project.id], true);
  assert.equal(await page.getByText('Knowledge · Hub').count(), 0);
  await page.getByRole('button', { name: 'Toggle files' }).click();
  await page.getByRole('button', { name: 'Browse files' }).click();
  await page.getByRole('combobox', { name: 'File browser root' }).click();
  await page.getByRole('listbox', { name: 'File browser root' }).getByRole('option', { name: /Exercise ·/ }).first().click();
  await page.getByRole('treeitem', { name: 'reference.md' }).waitFor();
  await page.getByRole('combobox', { name: 'File browser root' }).click();
  await page.getByRole('listbox', { name: 'File browser root' }).getByRole('option', { name: 'Exercise · Blender' }).click();
  await page.getByRole('treeitem', { name: 'model.blend' }).waitFor();
  await page.getByRole('button', { name: 'Toggle projects' }).click();
  await page.getByRole('button', { name: 'Edit Exercise' }).click();
  await page.getByRole('button', { name: 'Remove registration' }).click();
  await page.getByRole('alertdialog', { name: 'Remove workspace registration?' }).waitFor();
  await page.screenshot({ path: path.join(base, 'remove-registration-dialog.png') });
  await page.getByRole('alertdialog').getByRole('button', { name: 'Cancel' }).click();
  assert.equal((await service.projects.list()).some(item => item.id === project.id), true);
  await page.getByRole('button', { name: 'Unlink Main project' }).click();
  const mainUnlink = page.getByRole('alertdialog', { name: 'Unlink Main project?' });
  await mainUnlink.getByRole('combobox', { name: 'New main linked project' }).click();
  await page.getByRole('listbox', { name: 'New main linked project' }).getByRole('option', { name: 'Blender' }).click();
  await page.screenshot({ path: path.join(base, 'unlink-main-dialog.png') });
  await mainUnlink.getByRole('button', { name: 'Cancel' }).click();
  await page.getByRole('button', { name: 'Unlink Blender' }).click();
  await page.getByRole('alertdialog', { name: 'Unlink Blender?' }).getByRole('button', { name: 'Unlink project' }).click();
  await page.getByRole('alertdialog', { name: 'Unlink Blender?' }).waitFor({ state: 'hidden' });
  assert.deepEqual((await service.projects.get(project.id)).repositories.map(item => item.id), ['primary']);
  assert.equal(JSON.parse(await readFile(service.projects.workspacePath, 'utf8')).entities[0].repositoryId, null);
  assert.equal(await readFile(path.join(blender, 'model.blend'), 'utf8'), 'fixture model');
  assert.equal(await readFile(source, 'utf8'), '# Project knowledge');
  assert.deepEqual(errors, []);
  console.log(`Project UI passed: scoped hub tree, Inbox association, card creation, rail project tools and explicit external browsing. Screenshot: ${screenshot}`);
} finally { await browser?.close(); await service.close(); }
