// Run after npm run build. Isolated browser, repository and fake PTYs; no agent
// login, live conversation, Windows shortcut or production setting is touched.
import { chromium } from '@playwright/test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, cp } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parse as toml } from 'smol-toml';
import { createService } from '../server.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const repo = await mkdtemp(path.join(root, '.cache/workspace-ui-'));
for (const dir of ['workspace/test', 'knowledge', 'processes', '.claude/skills/example', '.agents/skills/example', 'inbox', 'projects']) await mkdir(path.join(repo, dir), { recursive: true });
await writeFile(path.join(repo, '.claude/skills/example/SKILL.md'), '# Example skill\n\n**Read me**\n');
const documentPath = path.join(repo, 'knowledge/notes.md');
await writeFile(documentPath, '# A useful document\n\n| Name | State |\n| --- | --- |\n| Example | Ready |\n\n**Bold text**\n');
const steps = Array.from({ length: 12 }, (_, index) => ({ name: `Step ${index + 1} - complete English title`, path: `step${index}.html` }));
for (const [index, step] of steps.entries()) await writeFile(path.join(repo, 'workspace/test', step.path), `<h1>Document ${index + 1}</h1><p>Readable content.</p>`);
await writeFile(path.join(repo, 'workspace/workspace.json'), JSON.stringify({ entities: [{ id: 'test', folder: 'test', title: 'Workspace test', category: 'test', created: '2026-09-15', status: 'active', steps }] }));
await cp(path.join(root, 'public/assets'), path.join(root, 'dist/assets'), { recursive: true });
const mcpHome = path.join(repo, 'fake-home'); await mkdir(path.join(mcpHome, '.codex'), { recursive: true });
await mkdir(path.join(mcpHome, '.codex/plugins/cache/local/unity/1.0'), { recursive: true });
await writeFile(path.join(repo, '.mcp.json'), JSON.stringify({ mcpServers: { 'fixture-tools': { type: 'http', url: 'https://fixture.example/mcp', headers: { Authorization: 'private-ui-fixture-token' } } } }));
await writeFile(path.join(repo, '.claude/settings.local.json'), JSON.stringify({ enableAllProjectMcpServers: true }));
await writeFile(path.join(mcpHome, '.codex/config.toml'), '[plugins."unity@local"]\nenabled = false\n[mcp_servers."global-tools"]\nurl="https://global.example/mcp"\n');
const service = await createService({ repo, uiDir: path.join(root, 'dist'), mcpOptions: { home: mcpHome, env: {}, probe: async () => ({ status: 'available', toolCount: 7 }) } });
const gameRoot = await mkdtemp(path.join(root, '.cache/game-ui-'));
const game = await service.projects.save({ name: 'Fixture Game', repositoryPath: gameRoot });
const writes = new Map();
for (const agent of ['codex', 'claude', 'kimi', 'shell']) {
  const session = service.sessions.make({ id: agent, name: `${agent} fixture`, agent, cwd: repo, status: 'running', open: true, pinned: false, createdAt: new Date().toISOString(), cols: 90, rows: 30 });
  service.sessions.items.set(agent, session); await service.sessions.hydrate(session);
  const received = []; writes.set(agent, received);
  session.process = { write: data => received.push(data), resize() {}, kill() {} };
  await new Promise(resolve => session.terminal.write(Array.from({ length: 400 }, (_, i) => `Fixture line ${String(i + 1).padStart(3, '0')} - readable terminal output\r\n`).join('') + '\x1b[?1000h\x1b[?1006h', resolve));
}
let browser;
try {
  browser = await chromium.launch({ headless: true, channel: process.env.MRMAK_TEST_BROWSER || 'msedge' });
  const context = await browser.newContext({ viewport: { width: 900, height: 800 }, permissions: ['clipboard-read', 'clipboard-write'] });
  const page = await context.newPage(); page.setDefaultTimeout(10000); page.setDefaultNavigationTimeout(30000);
  const errors = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto(service.urls.workspace + '#/test/0', { waitUntil: 'domcontentloaded' });
  for (let index = 0; index < 12; index++) { await page.getByRole('tab').nth(index).click(); await page.frameLocator('iframe.report-frame').getByRole('heading', { name: `Document ${index + 1}`, exact: true }).waitFor(); }
  let releaseReport;
  const delayedReport = new Promise(resolve => { releaseReport = resolve; });
  await page.route('**/workspace/test/step0.html', async route => { if (route.request().method() === 'GET') await delayedReport; await route.continue(); });
  await page.getByRole('tab').nth(0).click();
  try {
    await page.getByRole('status').filter({ hasText: 'Opening report' }).waitFor();
    assert.equal(await page.locator('iframe.report-frame').evaluate(element => getComputedStyle(element).visibility), 'hidden');
    assert.equal(await page.locator('.report-document').evaluate(element => getComputedStyle(element).backgroundColor), 'rgb(16, 17, 21)');
  } finally { releaseReport(); }
  await page.locator('.report-document[aria-busy=false]').waitFor();
  await page.getByRole('button', { name: 'Open Workspace help' }).click();
  const guide = page.getByRole('dialog', { name: 'Mr. Mik guide' });
  await guide.getByRole('heading', { name: 'Mr. Mik Workspace · Manual and reference' }).waitFor();
  await guide.getByRole('button', { name: /Settings and transferring a Hub/ }).click();
  await guide.getByText('Export · full', { exact: false }).first().waitFor();
  await guide.getByRole('textbox', { name: 'Search the guide' }).fill('MCP');
  assert.ok(await guide.locator('.help-site-nav-list button').count() > 0);
  await guide.getByRole('button', { name: 'Close guide' }).click();
  await guide.waitFor({ state: 'detached' });
  await page.getByRole('button', { name: 'Toggle settings' }).click();
  await page.getByRole('button', { name: 'Blue accent' }).click();
  await page.locator('html[data-accent-theme="blue"]').waitFor();
  assert.equal(await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--pink').trim()), '#83c5ff');
  assert.equal(JSON.parse(await readFile(path.join(repo, '.mrmak/settings.json'), 'utf8')).accentTheme, 'blue');
  const chatsTheme = await context.newPage();
  await chatsTheme.goto(service.urls.chats, { waitUntil: 'domcontentloaded' });
  await chatsTheme.locator('html[data-accent-theme="blue"]').waitFor();
  await chatsTheme.close();
  await page.getByRole('button', { name: 'Rose accent' }).click();
  await page.locator('html[data-accent-theme="rose"]').waitFor();
  await page.getByRole('button', { name: 'Close settings' }).click();
  assert.equal(await page.frameLocator('iframe.report-frame').locator('body').evaluate(element => getComputedStyle(element).scrollbarColor), 'rgb(81, 76, 89) rgb(17, 18, 23)');
  await page.unroute('**/workspace/test/step0.html');
  await page.route('**/workspace/test/step1.html', route => route.request().method() === 'HEAD' ? route.fulfill({ status: 404 }) : route.continue());
  await page.getByRole('tab').nth(1).click();
  await page.getByText('Page unavailable (404).', { exact: true }).waitFor();
  await page.unroute('**/workspace/test/step1.html');
  await page.getByRole('tab').nth(2).click();
  await page.locator('.report-document[aria-busy=false]').waitFor();
  await page.getByRole('button', { name: 'Toggle files', exact: true }).click();
  await page.getByRole('button', { name: 'Browse files', exact: true }).click();
  await page.getByRole('treeitem', { name: /^knowledge$/ }).click();
  await page.getByRole('treeitem', { name: /^notes.md/ }).click();
  await page.getByRole('heading', { name: 'A useful document' }).waitFor(); assert.equal(await page.locator('.mak-markdown table').count(), 1);
  await page.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByRole('textbox', { name: 'Edit notes.md' }).fill('# Edited document\n\nUnicode: русский 🐽\n');
  await page.getByRole('textbox', { name: 'Edit notes.md' }).press('Control+s');
  await page.getByText('Saved', { exact: true }).waitFor(); assert.match(await readFile(documentPath, 'utf8'), /русский 🐽/);
  await writeFile(documentPath, '# Changed by another agent\n');
  await page.getByRole('textbox', { name: 'Edit notes.md' }).fill('# My unsaved draft\n');
  await page.getByRole('button', { name: 'Save', exact: true }).click();
  await page.getByText(/This file changed on disk/).waitFor(); assert.match(await readFile(documentPath, 'utf8'), /another agent/);
  await page.getByRole('button', { name: 'Close file preview' }).click();
  await page.getByRole('treeitem', { name: /^notes.md/ }).click();
  await page.getByRole('heading', { name: 'My unsaved draft' }).waitFor();
  await page.getByRole('button', { name: 'Discard', exact: true }).click();
  await page.getByRole('heading', { name: 'Changed by another agent' }).waitFor();
  await page.getByRole('button', { name: 'Close file preview' }).click();
  await page.getByRole('treeitem', { name: /^notes.md/ }).click({ button: 'right' });
  await page.getByRole('menuitem', { name: 'Open in Explorer' }).waitFor();
  await page.getByRole('menuitem', { name: 'Move to Recycle Bin' }).click();
  await page.getByRole('alertdialog', { name: 'Move to Recycle Bin?' }).getByRole('button', { name: 'Cancel' }).click();
  assert.match(await readFile(documentPath, 'utf8'), /another agent/);
  await page.getByRole('button', { name: 'Main folders', exact: true }).click();
  await page.getByRole('button', { name: 'notes.md', exact: true }).click({ button: 'right' });
  await page.getByRole('menuitem', { name: 'Open in Explorer' }).waitFor();
  await page.getByRole('menuitem', { name: 'Move to Recycle Bin' }).click();
  await page.getByRole('alertdialog', { name: 'Move to Recycle Bin?' }).getByRole('button', { name: 'Cancel' }).click();
  assert.equal(await readFile(documentPath, 'utf8'), '# Changed by another agent\n');
  await page.getByRole('button', { name: 'Toggle skills', exact: true }).click();
    await page.getByRole('group', { name: 'Skill agent' }).getByRole('button', { name: 'Claude' }).click();
  await page.getByRole('treeitem', { name: /^example$/ }).click(); await page.getByRole('treeitem', { name: /^SKILL.md/ }).click();
  await page.getByRole('heading', { name: 'Example skill' }).waitFor();
  await page.getByRole('button', { name: 'Toggle mcp', exact: true }).click();
  await page.getByRole('heading', { name: 'fixture-tools', exact: true }).waitFor();
  assert.equal((await page.locator('.mcp-panel').innerText()).includes('private-ui-fixture-token'), false);
  await page.getByRole('button', { name: 'Check fixture-tools for Claude', exact: true }).click();
  await page.locator('[data-mcp-id="claude:fixture-tools"]').getByText('7 tools', { exact: true }).waitFor();
  await page.getByRole('combobox', { name: 'Filter MCP by agent' }).selectOption('codex');
  await page.getByRole('heading', { name: 'global-tools', exact: true }).waitFor();
  await page.getByRole('heading', { name: 'unity@local', exact: true }).waitFor();
  await page.locator('[data-mcp-id="codex:global-tools"]').getByRole('button', { name: 'Hide global-tools in Tools' }).click();
  await page.getByRole('heading', { name: 'global-tools', exact: true }).waitFor({ state: 'detached' });
  await page.getByRole('button', { name: 'Show hidden tools' }).click();
  await page.locator('[data-mcp-id="codex:global-tools"].is-hidden').getByRole('button', { name: 'Show global-tools in Tools' }).click();
  await page.getByRole('button', { name: 'Hide hidden tools' }).click();
  await page.getByRole('combobox', { name: 'Filter tools by type' }).selectOption('mcp');
  assert.equal(await page.locator('.mcp-server').count(), 1);
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('combobox', { name: 'global-tools global setting' }).selectOption('false');
  await page.locator('[data-mcp-id="codex:global-tools"] .mcp-state.disabled').waitFor();
  assert.equal(toml(await readFile(path.join(mcpHome, '.codex/config.toml'), 'utf8')).mcp_servers['global-tools'].enabled, false);
  await page.getByRole('combobox', { name: 'Filter tools by type' }).selectOption('plugin');
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('combobox', { name: 'unity@local global setting' }).selectOption('true');
  await page.waitForFunction(() => document.querySelector('select[aria-label="unity@local global setting"]')?.value === 'true');
  assert.equal(toml(await readFile(path.join(mcpHome, '.codex/config.toml'), 'utf8')).plugins['unity@local'].enabled, true);
  await page.getByRole('combobox', { name: 'Active workspace' }).selectOption(game.id);
  await page.getByRole('combobox', { name: 'Filter tools by type' }).selectOption('mcp');
  await page.getByRole('combobox', { name: 'global-tools project setting' }).selectOption('true');
  await page.waitForFunction(() => document.querySelector('select[aria-label="global-tools project setting"]')?.value === 'true');
  assert.equal(toml(await readFile(path.join(gameRoot, '.codex/config.toml'), 'utf8')).mcp_servers['global-tools'].enabled, true);
  await page.getByRole('combobox', { name: 'Active workspace' }).selectOption('');
  await page.getByRole('button', { name: '+ Add MCP server' }).click();
  await page.getByRole('heading', { name: 'Add MCP server' }).waitFor();
  await page.getByLabel('Server name').fill('managed_fixture');
  await page.getByLabel('MCP URL').fill('https://managed.example/mcp');
  page.once('dialog', dialog => dialog.accept());
  await page.getByRole('button', { name: 'Save definition' }).click();
  await page.getByText('managed_fixture · http', { exact: true }).waitFor();
  assert.equal((await readFile(path.join(mcpHome, '.codex/config.toml'), 'utf8')).includes('managed_fixture'), true);
  await page.getByRole('button', { name: 'Claude', exact: true }).click();
  await page.getByLabel('Server name').fill('claude_shared_fixture');
  await page.getByLabel('MCP URL').fill('https://claude.example/mcp');
  await page.getByRole('button', { name: 'Save definition' }).click();
  await page.getByText('claude_shared_fixture · http', { exact: true }).waitFor();
  assert.equal(JSON.parse(await readFile(path.join(mcpHome, '.claude.json'), 'utf8')).mcpServers.claude_shared_fixture.url, 'https://claude.example/mcp');
  await page.getByRole('button', { name: 'Back to Tools' }).click();
  await page.getByRole('combobox', { name: 'Filter MCP by agent' }).selectOption('claude');
  await page.getByRole('combobox', { name: 'Active workspace' }).selectOption(game.id);
  const inheritedClaude = page.locator('[data-mcp-id="claude:claude_shared_fixture"]');
  await inheritedClaude.getByRole('combobox', { name: 'claude_shared_fixture linked Claude MCP' }).click();
  await page.getByRole('listbox', { name: 'claude_shared_fixture linked Claude MCP' }).getByRole('option', { name: 'Off' }).click();
  await inheritedClaude.getByRole('combobox', { name: 'claude_shared_fixture linked Claude MCP' }).getByText('Off', { exact: true }).waitFor();
  assert.deepEqual(JSON.parse(await readFile(path.join(mcpHome, '.claude.json'), 'utf8')).projects[gameRoot].disabledMcpServers, ['claude_shared_fixture']);
  assert.equal((await readFile(path.join(repo, '.mcp.json'), 'utf8')).includes('private-ui-fixture-token'), true);
  await page.getByRole('button', { name: 'Close MCP', exact: true }).click();
  await page.goto(service.urls.chats);
  await page.getByRole('button', { name: 'New chat', exact: true }).click();
  const projectChoice = page.locator('.desk-dialog').getByRole('combobox', { name: 'Workspace', exact: true });
  await projectChoice.click();
  assert.equal(await page.getByRole('listbox', { name: 'Workspace' }).evaluate(element => getComputedStyle(element).backgroundColor), 'rgb(37, 35, 45)');
  await page.getByRole('listbox', { name: 'Workspace' }).getByRole('option', { name: 'Fixture Game' }).click();
  assert.match(await projectChoice.innerText(), /Fixture Game/);
  await page.locator('.desk-dialog').getByRole('button', { name: 'Close', exact: true }).click();
  const oldChat = await service.sessions.importConversation({ agent: 'codex', nativeId: '00000000-0000-0000-0000-000000000128', name: 'Old fixture', cwd: repo });
  await page.locator('.history-button').click();
  await page.getByRole('combobox', { name: 'History workspace' }).click();
  assert.equal(await page.getByRole('listbox', { name: 'History workspace' }).evaluate(element => getComputedStyle(element).backgroundColor), 'rgb(37, 35, 45)');
  await page.getByRole('listbox', { name: 'History workspace' }).getByRole('option', { name: 'All workspaces' }).click();
  const oldRow = page.locator('.history-item').filter({ hasText: 'Old fixture' });
  await oldRow.getByRole('combobox', { name: 'Associate Old fixture with workspace' }).waitFor();
  await oldRow.getByRole('combobox', { name: 'Associate Old fixture with workspace' }).click();
  assert.equal(await page.getByRole('listbox', { name: 'Associate Old fixture with workspace' }).evaluate(element => getComputedStyle(element).backgroundColor), 'rgb(37, 35, 45)');
  await page.getByRole('listbox', { name: 'Associate Old fixture with workspace' }).getByRole('option', { name: 'No association' }).click();
  await oldRow.getByRole('button', { name: 'Archive' }).click();
  await oldRow.waitFor({ state: 'detached' });
  await page.getByRole('button', { name: 'Archived', exact: true }).click();
  await oldRow.getByRole('button', { name: 'Restore' }).click();
  await oldRow.waitFor({ state: 'detached' });
  await page.getByRole('button', { name: 'All', exact: true }).click();
  await oldRow.getByLabel('More actions for Old fixture').click();
  await oldRow.getByRole('button', { name: 'Remove from Mr. Mik' }).click();
  const removal = page.getByRole('dialog', { name: 'Remove chat from Mr. Mik' });
  await removal.getByRole('heading', { name: 'Remove this chat?' }).waitFor();
  await removal.getByRole('button', { name: 'Cancel' }).last().click();
  assert.equal(service.sessions.items.has(oldChat.id), true);
  await oldRow.getByRole('button', { name: 'Remove from Mr. Mik' }).click();
  await removal.getByRole('button', { name: 'Remove from Mr. Mik' }).click();
  await oldRow.waitFor({ state: 'detached' });
  assert.equal(service.sessions.items.has(oldChat.id), false);
  await page.getByRole('button', { name: 'Close history' }).click();
  async function setTerminalFontSize(size) {
    await page.getByTitle('Chat options', { exact: true }).click();
    const control = page.locator('.font-control');
    const current = Number(await control.locator('span').last().innerText());
    const button = control.getByRole('button', { name: size > current ? '+' : '−', exact: true });
    for (let count = 0; count < Math.abs(size - current); count++) await button.click();
    await page.getByTitle('Chat options', { exact: true }).click();
  }
  // Check the actual terminal rows, not just the host box: FitAddon can size
  // a grid into parent padding and silently clip the CLI's bottom status row.
  for (const [width, height, fontSize] of [[535, 720, 13], [535, 497, 17], [900, 800, 13], [640, 480, 22]]) {
    await page.setViewportSize({ width, height });
    await setTerminalFontSize(fontSize);
    await page.waitForFunction(size => {
      const rows = document.querySelector('.xterm-rows');
      return rows && getComputedStyle(rows).fontSize === `${size}px`;
    }, fontSize);
    await page.waitForFunction(() => {
      const last = document.querySelector('.xterm-rows > :last-child')?.getBoundingClientRect();
      const host = document.querySelector('.terminal-host')?.getBoundingClientRect();
      const status = document.querySelector('.chat-status')?.getBoundingClientRect();
      return last && host && status && last.bottom <= host.bottom + .5 && last.bottom <= status.top - 4 && last.right <= host.right + .5;
    }, null, { timeout: 3000 });
  }
  await page.setViewportSize({ width: 900, height: 800 });
  await setTerminalFontSize(13);
  for (const agent of ['codex', 'claude', 'kimi', 'shell']) {
    await page.locator(`[data-chat-tab="${agent}"] [role="tab"]`).click();
    const screen = page.locator('.terminal-area .xterm-screen'); await screen.waitFor();
    await page.locator('.xterm-rows').filter({ hasText: 'Fixture line' }).waitFor();
    if (agent !== 'shell') {
      await screen.hover(); const before = await page.locator('.xterm-rows').innerText(); await page.mouse.wheel(0, -420);
      await page.waitForFunction(previous => document.querySelector('.xterm-rows')?.textContent !== previous, before);
      assert.notEqual(await page.locator('.xterm-rows').innerText(), before, 'Agent wheel scroll must move history even with mouse reporting enabled');
      await page.evaluate(() => navigator.clipboard.writeText('clipboard sentinel'));
      await page.locator('.xterm-helper-textarea').focus(); await page.keyboard.press('Control+c');
      assert.equal(await page.evaluate(() => navigator.clipboard.readText()), 'clipboard sentinel');
      // Shift overrides terminal mouse tracking so a row can be selected.
      await page.keyboard.down('Shift'); await screen.click({ position: { x: 120, y: 30 }, clickCount: 3 }); await page.keyboard.up('Shift');
      await page.keyboard.press('Control+c');
      assert.match(await page.evaluate(() => navigator.clipboard.readText()), /Fixture line/);
      assert.ok(writes.get(agent).every(data => !data.includes('\x03')), `${agent}: Ctrl+C must never reach PTY`);
    } else {
      await page.locator('.xterm-helper-textarea').focus(); await page.keyboard.press('Control+c');
      for (let i = 0; i < 20 && !writes.get(agent).includes('\x03'); i++) await new Promise(resolve => setTimeout(resolve, 20));
      assert.ok(writes.get(agent).includes('\x03'), 'PowerShell retains Ctrl+C interrupt');
    }
  }
  assert.deepEqual(errors, []);
  console.log('UI passed: 12 clickable wrapping tabs; Markdown preview/edit/save/conflict/draft; local Skills; MCP filtering, checks and hidden credentials; terminal bottom row visible across four window/font sizes; Codex/Claude/Kimi copy and scroll; PowerShell interrupt.');
} finally {
  await browser?.close();
  for (const session of service.sessions.items.values()) session.process = null;
  await service.close();
}
